// <auto-generated />
namespace SINU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fechatoken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fechatoken));
        
        string IMigrationMetadata.Id
        {
            get { return "201911011619467_fechatoken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
