USE [master]
GO
DROP LOGIN [User_SINU]
GO


CREATE LOGIN [User_SINU] WITH PASSWORD=N'SINU_User', DEFAULT_DATABASE=[SINU], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [Parametricas]
GO
DROP USER [User_SINU]
GO

CREATE USER [User_SINU] FOR LOGIN [User_SINU]
GO
ALTER ROLE [db_datareader] ADD MEMBER [User_SINU]
GO

USE [Seguridad]
GO
DROP USER [User_SINU]
GO

CREATE USER [User_SINU] FOR LOGIN [User_SINU]
GO
ALTER ROLE [db_datareader] ADD MEMBER [User_SINU]
ALTER ROLE [db_datawriter] ADD MEMBER [User_SINU]
ALTER ROLE [Seguridad_Executor] ADD MEMBER [User_SINU]
GO

USE [SINU]
GO
DROP USER [User_SINU]
GO

CREATE USER [User_SINU] FOR LOGIN [User_SINU]
GO
ALTER ROLE [db_datareader] ADD MEMBER [User_SINU]
ALTER ROLE [db_datawriter] ADD MEMBER [User_SINU]
ALTER ROLE [db_owner] ADD MEMBER [User_SINU]
GO
