//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antropometria
    {
        public int IdPostulantePersona { get; set; }
        public int Altura { get; set; }
        public decimal Peso { get; set; }
        public decimal IMC { get; set; }
        public int PerimCabeza { get; set; }
        public int PerimTorax { get; set; }
        public int PerimCintura { get; set; }
        public int PerimCaderas { get; set; }
        public int LargoPantalon { get; set; }
        public int LargoEntrep { get; set; }
        public int LargoFalda { get; set; }
        public int Cuello { get; set; }
        public int Calzado { get; set; }
    
        public virtual Postulante Postulante { get; set; }
    }
}
