//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public string NombreDato { get; set; }
        public string ValorDato { get; set; }
        public string TipoDato { get; set; }
        public string UsoDato { get; set; }
        public System.DateTime UltModif { get; set; }
        public bool Eliminado { get; set; }
        public int IdConfiguracion { get; set; }
    }
}
