//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaProgramada
    {
        public int IdConsulta { get; set; }
        public string NombreMenu { get; set; }
        public string DescripcionConsulta { get; set; }
        public int OrdenConsulta { get; set; }
        public string Link { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Parametros { get; set; }
    }
}
