//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataVerificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataVerificacion()
        {
            this.DataProblemaEncontrado = new HashSet<DataProblemaEncontrado>();
        }
    
        public int IdDataVerificacion { get; set; }
        public string Descripcion { get; set; }
        public int IdPantalla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataProblemaEncontrado> DataProblemaEncontrado { get; set; }
        public virtual VerificacionPantallas VerificacionPantallas { get; set; }
    }
}
