//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeclaracionJurada
    {
        public int IdDeclaracionJurada { get; set; }
        public string PoseeAntecedentes { get; set; }
        public string Antecedentes_Detalles { get; set; }
        public string EsAdicto { get; set; }
        public string Comentario { get; set; }
        public int IdInscripcion { get; set; }
    
        public virtual Inscripcion Inscripcion { get; set; }
    }
}
