//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delegacion_EstablecExamen
    {
        public int idOficinasYDelegaciones { get; set; }
        public int idDelegacion_EstablecExamen { get; set; }
        public int IdEstablecimientoRindeExamen { get; set; }
    
        public virtual EstablecimientoRindeExamen EstablecimientoRindeExamen { get; set; }
        public virtual OficinasYDelegaciones OficinasYDelegaciones { get; set; }
    }
}
