//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudio()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public bool Completo { get; set; }
        public Nullable<int> IdNiveldEstudio { get; set; }
        public int IdInstitutos { get; set; }
        public Nullable<double> Promedio { get; set; }
        public Nullable<int> CantidadMateriaAdeudadas { get; set; }
        public Nullable<int> ultimoAnioCursado { get; set; }
        public string NombreYPaisInstituto { get; set; }
        public bool CursandoUltimoAnio { get; set; }
    
        public virtual NiveldEstudio NiveldEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
