//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familiares
    {
        public int IdPostulantePersona { get; set; }
        public int IdPersona { get; set; }
        public int idParentesco { get; set; }
        public int IdFamiliar { get; set; }
        public bool Vive { get; set; }
        public bool ConVive { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Postulante Postulante { get; set; }
    }
}
