//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionEtapaEstado
    {
        public int IdSecuencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdInscripcionEtapaEstado { get; set; }
    
        public virtual Inscripcion Inscripcion { get; set; }
        public virtual Secuencia_EtapaEstado Secuencia_EtapaEstado { get; set; }
    }
}
