//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Familiares = new HashSet<Familiares>();
            this.PersonaIdioma = new HashSet<PersonaIdioma>();
            this.Estudio = new HashSet<Estudio>();
            this.SituacionOcupacional = new HashSet<SituacionOcupacional>();
            this.Interes = new HashSet<Interes>();
            this.ActividadMilitar = new HashSet<ActividadMilitar>();
            this.VerificacionPantallasCerradas = new HashSet<VerificacionPantallasCerradas>();
        }
    
        public string Apellido { get; set; }
        public string Nombres { get; set; }
        public int IdSexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public string IdReligion { get; set; }
        public string IdEstadoCivil { get; set; }
        public Nullable<System.DateTime> FechaCasamiento { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public int idTipoNacionalidad { get; set; }
        public int IdLugarNacimientoLocalidad { get; set; }
        public int IdDomicilioDNI { get; set; }
        public int IdDomicilioActual { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual Domicilio Domicilio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Familiares> Familiares { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoNacionalidad TipoNacionalidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaIdioma> PersonaIdioma { get; set; }
        public virtual Postulante Postulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudio> Estudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SituacionOcupacional> SituacionOcupacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interes> Interes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadMilitar> ActividadMilitar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerificacionPantallasCerradas> VerificacionPantallasCerradas { get; set; }
    }
}
