//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaIdioma
    {
        public int IdPersona { get; set; }
        public string CodIdioma { get; set; }
        public int Habla { get; set; }
        public int Lee { get; set; }
        public int Escribe { get; set; }
        public int IdPersonaIdioma { get; set; }
    
        public virtual NivelIdioma NivelIdioma { get; set; }
        public virtual NivelIdioma NivelIdioma1 { get; set; }
        public virtual NivelIdioma NivelIdioma2 { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
