//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postulante()
        {
            this.Familiares = new HashSet<Familiares>();
            this.Inscripcion = new HashSet<Inscripcion>();
            this.PostulanteViaje = new HashSet<PostulanteViaje>();
            this.DataProblemaEncontrado = new HashSet<DataProblemaEncontrado>();
            this.VerificacionPantallasCerradas = new HashSet<VerificacionPantallasCerradas>();
        }
    
        public string IdAspNetUser { get; set; }
        public int IdPersona { get; set; }
        public string ComoSeEntero { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdComoSeEntero { get; set; }
    
        public virtual Antropometria Antropometria { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Familiares> Familiares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostulanteViaje> PostulanteViaje { get; set; }
        public virtual ComoSeEntero ComoSeEntero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataProblemaEncontrado> DataProblemaEncontrado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerificacionPantallasCerradas> VerificacionPantallasCerradas { get; set; }
    }
}
