//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDataProblemaEncontrado
    {
        public string Apellido_Y_Nombres { get; set; }
        public string DNI { get; set; }
        public string DataVerificacion { get; set; }
        public string Comentario { get; set; }
        public int IdDataVerificacion { get; set; }
        public int IdDataProblemaEncontrado { get; set; }
        public int IdPostulantePersona { get; set; }
        public int IdPantalla { get; set; }
        public string Pantalla { get; set; }
    }
}
