//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDelegacion_EstablecExamen
    {
        public string Direccion { get; set; }
        public string Jurisdiccion { get; set; }
        public string Localidad { get; set; }
        public string Nombre { get; set; }
        public int IdOficinasYDelegaciones { get; set; }
        public int idDelegacion_EstablecExamen { get; set; }
        public int IdEstablecimientoRindeExamen { get; set; }
        public bool ACTIVO { get; set; }
    }
}
