//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExportacion_Escuelas
    {
        public int idaspirante { get; set; }
        public Nullable<int> Nroinscripcion { get; set; }
        public string NRODDNN { get; set; }
        public string NomDeleg { get; set; }
        public string NROMOD { get; set; }
        public string Modalidad { get; set; }
        public string ModalidadDescrip { get; set; }
        public string nroinscripto { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Piso { get; set; }
        public string Unidad { get; set; }
        public string Localidad { get; set; }
        public string idprovincia { get; set; }
        public string Provincia { get; set; }
        public string cpostal { get; set; }
        public string PAIS { get; set; }
        public string Loc_Prov_CP { get; set; }
        public string caracteristica { get; set; }
        public string telefono { get; set; }
        public string Email { get; set; }
        public string opcioncuerpo1 { get; set; }
        public string opcioncuerpo2 { get; set; }
        public string sexo { get; set; }
        public int iddelegacion { get; set; }
        public string Deleg { get; set; }
        public string dni { get; set; }
        public string nacidoen { get; set; }
        public Nullable<System.DateTime> fechanac { get; set; }
        public string nacionalidad { get; set; }
        public string rindeen { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public string nativo { get; set; }
        public string poropcion { get; set; }
        public string cuil_a { get; set; }
        public string cuil_dv { get; set; }
        public string CUIL { get; set; }
        public string celular_carac { get; set; }
        public string celular { get; set; }
        public string calle_ev { get; set; }
        public string numero_ev { get; set; }
        public string piso_ev { get; set; }
        public string unidad_ev { get; set; }
        public string localidad_ev { get; set; }
        public string idprovincia_ev { get; set; }
        public string PROV_ev { get; set; }
        public string cpostal_ev { get; set; }
        public string Tiene_Hijos { get; set; }
        public string Cant_Varones { get; set; }
        public string Cant_Mujeres { get; set; }
        public string convive { get; set; }
        public string ifaa { get; set; }
        public string Cod_Estad_Civ { get; set; }
        public string EstadoCivil { get; set; }
        public string edadenanos { get; set; }
        public string edadenmeses { get; set; }
        public string religion { get; set; }
        public Nullable<int> nrocalzado { get; set; }
        public Nullable<int> nrocuello { get; set; }
        public Nullable<int> Altura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> perimetrotorax { get; set; }
        public Nullable<int> perimetrocintura { get; set; }
        public Nullable<int> LargoPantalon { get; set; }
        public Nullable<int> largoentrepierna { get; set; }
        public Nullable<int> LargoFalda { get; set; }
        public string id_provincia_esta { get; set; }
        public string orientacion { get; set; }
        public string solicitoesnm { get; set; }
        public string ingresoesnm { get; set; }
        public string causadenoingreso { get; set; }
        public string causadebaja { get; set; }
        public string motivobaja { get; set; }
        public string fechanoingresobaja { get; set; }
        public string alumnomilitar { get; set; }
        public string institutomilitar { get; set; }
        public string causabajainst { get; set; }
        public string motivobajainst { get; set; }
        public string fechabajainst { get; set; }
        public string OcupacionActual { get; set; }
        public string textoorientacion { get; set; }
        public string permanenciad { get; set; }
        public string permanenciam { get; set; }
        public string permanenciaa { get; set; }
        public string jerarquiaa { get; set; }
        public string permanenciafd { get; set; }
        public string permanenciafm { get; set; }
        public string permanenciafa { get; set; }
        public string jerarquiafa { get; set; }
        public string situaciono { get; set; }
        public string oficio { get; set; }
        public string textooficio { get; set; }
        public int viajesext { get; set; }
        public string textopais { get; set; }
        public string VIAJES { get; set; }
        public string motivoingreso { get; set; }
        public string gradoactual { get; set; }
        public string destinoactual { get; set; }
        public string bajaactual { get; set; }
        public string fuerzaactual { get; set; }
        public string agrupacivil { get; set; }
        public Nullable<bool> finalizoestudiossec { get; set; }
        public string establecimiento { get; set; }
        public string local_esta { get; set; }
        public string PROV_Esta { get; set; }
        public Nullable<int> debematerias { get; set; }
        public Nullable<int> deudamat { get; set; }
        public string nivelestudios { get; set; }
        public Nullable<int> anioscursados { get; set; }
        public string carrera { get; set; }
        public string otrosestable { get; set; }
        public string otralocalidad { get; set; }
        public string TituloSec { get; set; }
        public string idioma1 { get; set; }
        public string idioma1habla { get; set; }
        public string idioma1lee { get; set; }
        public string idioma1escribe { get; set; }
        public string idioma2 { get; set; }
        public string idioma2habla { get; set; }
        public string idioma2lee { get; set; }
        public string Idiomas { get; set; }
        public string prestaservicioffaa { get; set; }
        public string fuerza { get; set; }
        public string gradodestinobaja { get; set; }
        public string fechabajafuerza { get; set; }
        public string ActividadMilitar { get; set; }
    }
}
