//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExportacionDatosBasicos
    {
        public string nroinscripto { get; set; }
        public string Apellido { get; set; }
        public string Nombres { get; set; }
        public string sexo { get; set; }
        public string Deleg { get; set; }
        public string DNI { get; set; }
        public string fechanac { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string celular_carac { get; set; }
        public string Celular { get; set; }
        public string C__ { get; set; }
        public Nullable<int> IdPostulantePersona { get; set; }
        public int IdInscripcion { get; set; }
        public int IdConvocatoria { get; set; }
        public string IdModalidad { get; set; }
        public Nullable<int> IdCarreraOficio { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string ESTADO { get; set; }
        public int IdOficinasYDelegaciones { get; set; }
        public string Etapa { get; set; }
        public string EstadoEtapa { get; set; }
        public string CarreraUoficio { get; set; }
    }
}
