//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGruposYCarreras
    {
        public string IdGrupoCarrOficio { get; set; }
        public string Descripcion { get; set; }
        public string Personal { get; set; }
        public string CarreraUoficio { get; set; }
        public string Pers { get; set; }
        public Nullable<int> IdCarreraOficio { get; set; }
        public Nullable<int> EdadMinCAutoriz { get; set; }
        public Nullable<int> EdadMin { get; set; }
        public Nullable<int> EdadMax { get; set; }
        public Nullable<System.DateTime> Edad_a_fecha { get; set; }
        public Nullable<int> AlturaMinF { get; set; }
        public Nullable<int> AlturaMinM { get; set; }
        public Nullable<int> IMC_min { get; set; }
        public Nullable<int> IMC_max { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> IdResGrupo { get; set; }
    }
}
