//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInscriptosYConvocatorias
    {
        public int IdInscripcion { get; set; }
        public string IdModalidad { get; set; }
        public string IdGrupoCarrOficio { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public string NombreInst { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Proceso { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Proceso { get; set; }
        public Nullable<int> IdCarreraOficio { get; set; }
        public int IdConvocatoria { get; set; }
        public int IdPeriodoInscripcion { get; set; }
        public Nullable<int> IdPostulantePersona { get; set; }
        public Nullable<int> IdDelegacionOficinaIngresoInscribio { get; set; }
    }
}
