//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInscriptosYRestriccionesCount
    {
        public string IdModalidad { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Proceso { get; set; }
        public int IdConvocatoria { get; set; }
        public Nullable<int> SubTotal_Convoc { get; set; }
        public Nullable<int> AlturaProblema { get; set; }
        public Nullable<int> AlturaSinCargar { get; set; }
        public Nullable<int> AlturaOK { get; set; }
        public string Alturacheck { get; set; }
        public Nullable<int> IMCProblema { get; set; }
        public Nullable<int> IMCSinCargar { get; set; }
        public Nullable<int> IMCOK { get; set; }
        public string IMCCheck { get; set; }
        public Nullable<int> EdadProblema { get; set; }
        public Nullable<int> EdadSinCargar { get; set; }
        public Nullable<int> EdadOK { get; set; }
        public string EdadCheck { get; set; }
        public Nullable<int> EstadoCivilProblema { get; set; }
        public Nullable<int> EstadoCivilSinCargar { get; set; }
        public Nullable<int> EstadoCivilOK { get; set; }
        public string EstadoCivilCheck { get; set; }
    }
}
