//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInscriptosConTitulosProblemasCount
    {
        public int Idconvocatoria { get; set; }
        public string IdModalidad { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Proceso { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CantInscXProblema { get; set; }
    }
}
