//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInstitucionesConvocadasYCarrerasAsociadas
    {
        public int IdInstitucion { get; set; }
        public string IdGrupoCarrOficio { get; set; }
        public string CarreraUoficio { get; set; }
        public string Personal { get; set; }
        public int IdCarreraOficio { get; set; }
        public int IdConvocatoria { get; set; }
    }
}
