//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vModalidadYDocumento
    {
        public string IdModalidad { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public bool Obligatorio { get; set; }
        public Nullable<int> Orden { get; set; }
        public int IdTipoDocPresentado { get; set; }
    }
}
