//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOficDeleg_EstablecimientoRindExamen
    {
        public string OficinaDelegacion { get; set; }
        public string Establecimiento { get; set; }
        public string Localidad { get; set; }
        public string Comentario { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public int IdOficinasYDelegaciones { get; set; }
        public Nullable<int> IdEstablecimientoRindeExamen { get; set; }
    }
}
