//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPersona_Antropometria
    {
        public string Email { get; set; }
        public string Genero { get; set; }
        public Nullable<int> Altura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> IMC { get; set; }
        public Nullable<int> PerimCabeza { get; set; }
        public Nullable<int> PerimTorax { get; set; }
        public Nullable<int> PerimCintura { get; set; }
        public Nullable<int> PerimCaderas { get; set; }
        public Nullable<int> LargoPantalon { get; set; }
        public Nullable<int> LargoEntrep { get; set; }
        public Nullable<int> LargoFalda { get; set; }
        public Nullable<int> Cuello { get; set; }
        public Nullable<int> Calzado { get; set; }
        public int IdPersona { get; set; }
    }
}
