//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPersona_SituacionOcupacional
    {
        public int IdPersona { get; set; }
        public int IdEstadoOcupacional { get; set; }
        public int IdSituacionOcupacional { get; set; }
        public string EstadoOcupacional { get; set; }
        public string Descripcion { get; set; }
        public string OcupacionActual { get; set; }
        public string DomicilioLaboral { get; set; }
        public Nullable<int> AniosTrabajados { get; set; }
        public string Oficio { get; set; }
        public bool CargaOcupacionActual { get; set; }
        public string Explicacion { get; set; }
        public string DescInteres { get; set; }
    }
}
