//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPersona_DatosPer
    {
        public string Email { get; set; }
        public int IdPersona { get; set; }
        public string CUIL { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> edad { get; set; }
        public string IdEstadoCivil { get; set; }
        public string EstadoCivil { get; set; }
        public string IdReligion { get; set; }
        public string Religion { get; set; }
        public int idTipoNacionalidad { get; set; }
        public string Nacionalidad { get; set; }
        public string IdModalidad { get; set; }
        public Nullable<int> IdCarreraOficio { get; set; }
        public Nullable<int> IdInscripcion { get; set; }
        public string Apellido { get; set; }
        public string Nombres { get; set; }
    }
}
