//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProvincia_Depto_Localidad
    {
        public string Provincia { get; set; }
        public string DepartPartido { get; set; }
        public string Localidad { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public int IdLocalidad { get; set; }
    }
}
