//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSecuencia_EtapaEstadoNoRechazados
    {
        public int IdSecuencia { get; set; }
        public int IdEtapa { get; set; }
        public string Etapa { get; set; }
        public int IdEstado { get; set; }
        public string Estado { get; set; }
        public int Anterior { get; set; }
        public int Siguiente { get; set; }
    }
}
