//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUsuariosAdministrativos
    {
        public string codGrupo { get; set; }
        public string Email { get; set; }
        public string Delegacion { get; set; }
        public Nullable<int> IdOficinasYDelegaciones { get; set; }
        public string Destino { get; set; }
        public string mr { get; set; }
        public string Grado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Comentario { get; set; }
        public System.DateTime FechUltimaAct { get; set; }
    }
}
